### ISSUE TITLE
[MultiPerspective] Need update rtsp lib for latest ksylive version

### ISSUE THREAD

**Issue by thanhbc** [ksvc/KSYDiversityLive_Android#58]
Hello developers.
When I played around with MultiPerspective demo seems ok. but if I using gradle for ksylive lib seem need update rstp lib also
```gradle
    compile 'com.ksyun.media:libksylive-java:2.4.3'
    compile 'com.ksyun.media:libksylive-arm64:2.4.3'
    compile 'com.ksyun.media:libksylive-armv7a:2.4.3'
    compile 'com.ksyun.media:libksylive-x86:2.4.3'
```

here is the crash
```
09-05 18:45:44.891 21089-21251/com.ksyun.media.streamer.demo E/AndroidRuntime: FATAL EXCEPTION: EncodeThread
                                                                               Process: com.ksyun.media.streamer.demo, PID: 21089
                                                                               java.lang.NoSuchMethodError: No virtual method clone()Lcom/ksyun/media/streamer/framework/AudioBufFrame; in class Lcom/ksyun/media/streamer/framework/AudioBufFrame; or its super classes (declaration of 'com.ksyun.media.streamer.framework.AudioBufFrame' appears in /data/app/com.ksyun.media.streamer.demo-2/base.apk)
                                                                                   at com.ksyun.media.rtspserver.rtsp.RtspServer.a(RtspServer.java:192)
                                                                                   at com.ksyun.media.rtspserver.rtsp.RtspServer.a(RtspServer.java:62)
                                                                                   at com.ksyun.media.rtspserver.rtsp.RtspServer$AudioSinkPin.onFrameAvailable(RtspServer.java:178)
                                                                                   at com.ksyun.media.rtspserver.rtsp.RtspServer$AudioSinkPin.onFrameAvailable(RtspServer.java:170)
                                                                                   at com.ksyun.media.streamer.framework.SrcPin.onFrameAvailable(SrcPin.java:44)
                                                                                   at com.ksyun.media.streamer.framework.PinAdapter$1.onFrameAvailable(PinAdapter.java:20)
                                                                                   at com.ksyun.media.streamer.framework.SrcPin.onFrameAvailable(SrcPin.java:44)
                                                                                   at com.ksyun.media.streamer.encoder.Encoder.g(Encoder.java:439)
                                                                                   at com.ksyun.media.streamer.encoder.AVCodecAudioEncoder.onEncoded(AVCodecAudioEncoder.java:139)
                                                                                   at com.ksyun.media.streamer.encoder.AVEncoderWrapper.onEncoded(AVEncoderWrapper.java:82)
                                                                                   at com.ksyun.media.streamer.encoder.AVEncoderWrapper._open_audio(Native Method)
                                                                                   at com.ksyun.media.streamer.encoder.AVEncoderWrapper.a(AVEncoderWrapper.java:48)
                                                                                   at com.ksyun.media.streamer.encoder.AVCodecAudioEncoder.a(AVCodecAudioEncoder.java:47)
                                                                                   at com.ksyun.media.streamer.encoder.Encoder$4.handleMessage(Encoder.java:505)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
```

cc @chriszeng87

**Comment by chriszeng87** [comment]
Sorry, their's no plan to update MultiPerspective lib in the near future.

**Comment by thanhbc** [comment]
noted. Thanks
